**SWATHI P**

**CB.EN.U4CSE19353**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
revs = pd.read_csv('/content/drive/MyDrive/Machine Learning/revs_final.csv',  error_bad_lines=False)
revs.head()

reviewerID        asin  ... rating  sentiment
0   A2QK1U70OJ74P  B000FA64PA  ...      3          0
1  A3SZMGJMV0G16C  B000FA64PK  ...      3          1
2  A38Z3Q6DTDIH9J  B000FA64PK  ...      3          0
3  A3SZMGJMV0G16C  B000FA64QO  ...      2          0
4  A22CW0ZHY3NJH8  B000FA64QO  ...      3          0

[5 rows x 5 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = revs.loc[revs['sentiment'] == 1]
df.head()

reviewerID        asin  ... rating  sentiment
1   A3SZMGJMV0G16C  B000FA64PK  ...      3          1
5   A3SZMGJMV0G16C  B000FBFMVG  ...      3          1
7   A3SZMGJMV0G16C  B000FC1BN8  ...      3          1
13   ADXAE3UOGPUN4  B000FC26RI  ...      3          1
24   A9FVWRHMM550F  B000GFK7L6  ...      1          1

[5 rows x 5 columns]

In [ ]:
counts1=df['reviewerID'].value_counts() 
counts=df['asin'].value_counts()

In [ ]:
counts1

A13QTZ8CIMHHG4    224
A2WZJDFX12QXKD    177
A37LY77Q2YPJVL    150
A320TMDV6KCFU     143
A3PTWPKPXOG8Y5    131
                 ... 
A3RZ0HT9P7VFR0      1
A2BLQP7CWQX8AF      1
AJ9IPJR2KHQNR       1
A3AOJ120MH62T3      1
AY63QKPC0760Y       1
Name: reviewerID, Length: 50534, dtype: int64

In [ ]:
counts

B006GWO5WK    199
B00BTIDW4S    131
B00H0V069M     96
B00BSX4U04     87
B00JDYC5OI     80
             ... 
B00H324XOW      1
B009W2TFS0      1
B00K7BK1GU      1
B00GV3XQ8I      1
B0087NVG2I      1
Name: asin, Length: 48832, dtype: int64

In [ ]:
df1=df[df['reviewerID'].isin(counts1[counts1 >=30].index)]
df1.shape

(12201, 5)

In [ ]:
df2=df1[df1['asin'].isin(counts[counts >= 10].index)]
df2.shape

(1681, 5)

In [ ]:
# cold user - based on popularity
ratings_sum = pd.DataFrame(df2.groupby(['asin'])['rating'].sum()).rename(columns = {'rating': 'ratings_sum'})
top10 = ratings_sum.sort_values('ratings_sum', ascending = False).head(10)
top10


ratings_sum
asin                   
B00BCFWJ7E           28
B00BT0J8ZS           27
B00DXIFORA           25
B00HKMUFU6           25
B00DQTZOH6           24
B005C5YZ86           22
B00E7IWEFU           20
B00CEF014E           20
B00CJ3UPTW           19
B00B6JFKNG           19

In [ ]:
ratingsd=df2.pivot(index='asin',columns= 'reviewerID',values='rating').fillna(0)
ratingsd.head()

reviewerID  A10Y597K071WTQ  A1168ILANAUMV8  ...  AXIO51VZN815F  AYDMB9RBJMTBR
asin                                        ...                              
B000JMLBHU             0.0             0.0  ...            0.0            0.0
B001BXNQ2O             0.0             0.0  ...            0.0            0.0
B002AJ7X2C             0.0             0.0  ...            0.0            0.0
B0030CMJEK             0.0             0.0  ...            0.0            0.0
B0038KX8S0             0.0             0.0  ...            0.0            0.0

[5 rows x 216 columns]

In [ ]:
ratingsd.shape

(1104, 216)

In [ ]:

from sklearn.model_selection import train_test_split
traind, testd = train_test_split(ratingsd, test_size=0.30,random_state=42)

In [ ]:
train = traind.to_numpy()
test = testd.to_numpy()

In [ ]:
sparsity = float(len(train.nonzero()[0]))
sparsity /= (train.shape[0] * train.shape[1])
sparsity *= 100
print ('Sparsity: {:5.2f}%'.format(sparsity))

Sparsity:  0.71%


In [ ]:
def item_similarity(ratings, epsilon=1e-9):
    # epsilon -> for handling dived-by-zero errors
    sim = ratings.T.dot(ratings) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [ ]:
item_sim = item_similarity(train)

In [ ]:
def predict_item(ratings, similarity):
    return ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [ ]:
item_prediction = predict_item(train, item_sim)

In [ ]:
item_prediction[:4, :4]

array([[1.22877004e-11, 1.86269525e-01, 1.14434989e-11, 1.11501067e-11],
       [1.44626953e-11, 1.46160215e-11, 1.34690653e-11, 1.31237409e-11],
       [2.97453732e-11, 3.00607185e-11, 2.77017778e-11, 2.69915503e-11],
       [6.07255151e-11, 6.13692962e-11, 5.65534921e-11, 2.19843926e+00]])

In [ ]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

In [ ]:
print ('Item-based CF MSE: ' + str(get_mse(item_prediction, test)))

Item-based CF MSE: 19.302640715714443


In [ ]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(traind) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pm=pd.DataFrame(cosine_similarity(r_mat_tr))
#pm.head()
ctrain = cosine_similarity(r_mat_tr)

[0.02834594 0.02487422 0.01728777 0.01917014 0.01679008 0.01560585
 0.0151438  0.01503328 0.01450151 0.01375018 0.01322067 0.01264874
 0.01216288 0.01213211 0.01088275 0.01088754 0.0109368  0.01055127
 0.01055451 0.01026407 0.01019343 0.0100883  0.01000507 0.00977913
 0.00968173 0.00954465 0.00941933 0.00925724 0.00898387 0.00898501
 0.0087169  0.00835679 0.00841972 0.00835713 0.0082135  0.00817363
 0.00818019 0.00791394 0.00793514 0.00774985 0.0077055  0.00761858
 0.00762692 0.00750276 0.00725557 0.00715011 0.00712578 0.0070079
 0.00689025 0.00682509]
0.545407118772279


In [ ]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pmtt=pd.DataFrame(cosine_similarity(r_mat_tr))
#print (pmtt[:2])
#pmtt.head()

[0.03509543 0.03759686 0.02895198 0.02518443 0.02245581 0.02079457
 0.019341   0.01699439 0.01758556 0.01683619 0.01632832 0.01432504
 0.01510865 0.01461965 0.01452411 0.0137423  0.01371695 0.01347772
 0.01340526 0.01288502 0.01251401 0.01223949 0.01216131 0.01134466
 0.0114169  0.01109068 0.01114789 0.01069172 0.01074559 0.01046162
 0.01037604 0.00968051 0.00960401 0.0095284  0.0093674  0.00933171
 0.00912085 0.00905085 0.00895132 0.00890627 0.00888717 0.00876833
 0.00865322 0.00842112 0.00822813 0.00778818 0.00765033 0.00769073
 0.00729853 0.0070083 ]
0.6710944994670791


In [ ]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pmtt=pd.DataFrame(cosine_similarity(r_mat_tr))
#print (pmtt[:2])
#pmtt.head()
ctest = cosine_similarity(r_mat_tr)

[0.03509543 0.03759686 0.02895198 0.02518443 0.02245581 0.02079457
 0.019341   0.01699439 0.01758556 0.01683619 0.01632832 0.01432504
 0.01510865 0.01461965 0.01452411 0.0137423  0.01371695 0.01347772
 0.01340526 0.01288502 0.01251401 0.01223949 0.01216131 0.01134466
 0.0114169  0.01109068 0.01114789 0.01069172 0.01074559 0.01046162
 0.01037604 0.00968051 0.00960401 0.0095284  0.0093674  0.00933171
 0.00912085 0.00905085 0.00895132 0.00890627 0.00888717 0.00876833
 0.00865322 0.00842112 0.00822813 0.00778818 0.00765033 0.00769073
 0.00729853 0.0070083 ]
0.6710944994670791


In [ ]:
print (' CF MSE: ' + str(get_mse(ctrain, ctest)))

 CF MSE: 0.04488844931657428


In [ ]:
df2 = df2.sort_values(by='rating')
df2 = df2.reset_index(drop=True)
count_users = df2.groupby("reviewerID", as_index=False).count()

In [ ]:
count = df2.groupby("asin", as_index=False).mean()

In [ ]:
items_df = count[['asin']]
items_df.head()
print(len(items_df))

1104


In [ ]:
users_df = count_users[['reviewerID']]
users_df.head()
print(len(users_df))

216


In [ ]:
users_list = users_df.values
len(users_list)

216

In [ ]:
df_clean_matrix = df2.pivot(index='asin', columns='reviewerID', values='rating').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).to_numpy()
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.03894928, -0.03894928, -0.03894928, ..., -0.03894928,
        -0.03894928, -0.03894928],
       [-0.05253623, -0.05253623, -0.05253623, ..., -0.05253623,
        -0.05253623, -0.05253623],
       [-0.01268116, -0.01268116, -0.01268116, ..., -0.01268116,
        -0.01268116, -0.01268116],
       ...,
       [-0.00905797, -0.00905797, -0.00905797, ..., -0.00905797,
        -0.00905797, -0.00905797],
       [-0.00815217, -0.00815217, -0.00815217, ..., -0.00815217,
        -0.00815217, -0.00815217],
       [-0.01811594, -0.01811594, -0.01811594, ..., -0.01811594,
        -0.01811594, -0.01811594]])

In [ ]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

In [ ]:
sigma = np.diag(sigma)

In [ ]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['reviewerID'] = users_df
preds_df.set_index('reviewerID', inplace=True)
preds_df.head()

asin            B000JMLBHU  B001BXNQ2O  ...  B00LLI4V82  B00LLWDUDK
reviewerID                              ...                        
A10Y597K071WTQ    0.033144    0.030145  ...    0.042839    0.018721
A1168ILANAUMV8    0.056135    0.057110  ...    0.051733    0.050346
A11US7VEC93CT6    0.014057    0.014482  ...    0.013722    0.013504
A135NSTCX38DEI    0.019271    0.020817  ...    0.012814    0.015231
A13D5S4OXQUPRM    0.004950    0.005086  ...    0.004780    0.004842

[5 rows x 1104 columns]

In [ ]:
preds_df.shape

(216, 1104)

In [ ]:

def recommend_it(predictions_df, itm_df, original_ratings_df, num_recommendations=10,ruserId='A13QTZ8CIMHHG4'):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc[ruserId].sort_values(ascending=False)
    
    # Get the user's data and merge in the item information.
    user_data = original_ratings_df[original_ratings_df.reviewerID == ruserId]
    user_full = (user_data.merge(itm_df, how = 'left', left_on = 'asin', right_on = 'asin').
                     sort_values(['rating'], ascending=False)
                 )

    print ('User {0} has already purchased {1} items.'.format(ruserId, user_full.shape[0]))
    print ('Recommending the highest {0} predicted  items not already purchased.'.format(num_recommendations))
    
    # Recommend the highest predicted rating items that the user hasn't bought yet.
    recommendations = (itm_df[~itm_df['asin'].isin(user_full['asin'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'asin',
               right_on = 'asin').
         rename(columns = {ruserId: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    topk=recommendations.merge(original_ratings_df,left_index = True, right_on = 'asin',left_on='asin').drop_duplicates(
    ['asin'])[['asin']]

    return topk

In [ ]:
recommend_it(preds_df, items_df, df2, 8)

User A13QTZ8CIMHHG4 has already purchased 7 items.
Recommending the highest 8 predicted  items not already purchased.


asin
781  B0089H8AQ2
614  B009IAMQIW
102  B00GGRBCNU
237  B009JWLKEU
993  B00C8OZB7I
583  B00D4B53UE
994  B00G5XIXDM
152  B007UAUPT4